version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - ./mysql:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    ports:
      - "9000:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
    volumes:
      - ./wordpress:/var/www/html
